{{- $namespace := .Release.Namespace -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shob-server-{{ $namespace }}-pv
  namespace: {{ $namespace }}
spec:
  capacity:
    storage: 30Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.content_shob_server }}
    server: {{ .Values.nfs }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shob-ui-{{ $namespace }}-pv
  namespace: {{ $namespace }}
spec:
  capacity:
    storage: 30Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.content_shob_ui }}
    server: {{ .Values.nfs }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shob-pyland-{{ $namespace }}-pv
  namespace: {{ $namespace }}
spec:
  capacity:
    storage: 30Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.rti_lic }}
    server: {{ .Values.nfs }}
